### ISSUE TITLE
Config properties should be fetched via the Config API

### ISSUE THREAD

**Issue by NightJar** [chtombleson/silverstripe-flowchart#3]
https://github.com/chtombleson/silverstripe-flowchart/blob/047546abe7769fcdef7402c7eddc0465bccba802/src/model/FlowchartQuestion.php#L179

`static` here causes issues in subclasses, as the property is private - it cannot be accessed by subclasses. I think `self` might fix this, but it looks as if it is intended to be used as a config property - in this case it should be `$this->config()->get('flowcharts_asset_folder')` instead.

**Comment by chtombleson** [comment]
Afternoon,

If you are sub-classing the FlowchartQuestion model you can just overwrite the FolderName function in the sub-class and have it return whatever you like. It was never intended to point at a configuration variable.

Cheers,
Chris Tombleson
